#!/bin/bash

source $HOME/git/installation/functions_common

update_all() {
  brew update
  brew upgrade
  install_go_packages
  rustup install stable
  install_cargo_packages
  install_opam_packages
  install_vscode_extensions
  install_dotnet_tools
  install_gems
  update_python_packages
  install_gcpdiag
  flutter upgrade
  install_gh_extensions
  $HOME/git/installation/uv_tools_install.sh
  install_pipx_packages
  install_reddit_tui
  install_hugo
  update_protobuf_flutter
}

install_all() {
  install_have
  install_another_redis_desktop_manager
  install_gcpdiag
  rustup install stable
  install_slack_cli
  $HOME/git/installation/uv_tools_install.sh
  install_pipx_packages
  install_reddit_tui
}

install_azure_data_studio_extensions() {
  cat $HOME/git/installation/azuredatastudio.extensions | xargs -n 1 /usr/bin/azuredatastudio --force --install-extension
}

install_opam_packages() {
  opam update
  cat $HOME/git/installation/opam_packages | xargs -n 1 opam install -y
}

install_another_redis_desktop_manager() {
  INSTALL_DIR=$(mktemp -d)
  source $HOME/git/installation/versions-on-github

  curl -o $INSTALL_DIR/another-redis-desktop-manager.dmg -sSL https://github.com/qishibo/AnotherRedisDesktopManager/releases/download/v${VERSION_QISHIBO_ANOTHERREDISDESKTOPMANAGER}/Another-Redis-Desktop-Manager-M1-arm64-${VERSION_QISHIBO_ANOTHERREDISDESKTOPMANAGER}.dmg
  open $INSTALL_DIR/another-redis-desktop-manager.dmg
}

install_gems() {
  cat $HOME/git/installation/gem-list | xargs -n 1 brew-gem install
}

install_kubelogin() {
  INSTALL_DIR=$(mktemp -d)
  source $HOME/git/installation/versions-on-github

  curl -o $INSTALL_DIR/kubelogin.zip -sSL https://github.com/Azure/kubelogin/releases/download/v${VERSION_AZURE_KUBELOGIN}/kubelogin-darwin-arm64.zip
  unzip $INSTALL_DIR/kubelogin.zip -d $INSTALL_DIR/
  chmod +x $INSTALL_DIR/bin/darwin_arm64/kubelogin
  sudo /bin/mv -f $INSTALL_DIR/bin/darwin_arm64/kubelogin /usr/local/bin/
}

install_krew() {
  pushd $PWD

  set -x; cd "$(mktemp -d)" &&
  OS="$(uname | tr '[:upper:]' '[:lower:]')" &&
  ARCH="$(uname -m | sed -e 's/x86_64/amd64/' -e 's/\(arm\)\(64\)\?.*/\1\2/' -e 's/aarch64$/arm64/')" &&
  KREW="krew-${OS}_${ARCH}" &&
  curl -fsSLO "https://github.com/kubernetes-sigs/krew/releases/latest/download/${KREW}.tar.gz" &&
  tar zxvf "${KREW}.tar.gz" &&
  ./"${KREW}" install krew

  popd
}

install_krew_packages() {
  curl -sSL https://raw.githubusercontent.com/alexhokl/installation/master/krew_list \
    | xargs -n 1 kubectl krew install
}

install_d2() {
  curl -fsSL https://d2lang.com/install.sh | sh -s --
}

install_task_completion() {
  sudo curl -o /opt/homebrew/etc/bash_completion.d/task.bash -sSL https://raw.githubusercontent.com/go-task/task/master/completion/bash/task.bash
}

install_gcloud_sql_proxy() {
  sudo curl -o /usr/local/bin/cloud-sql-proxy -sSL https://storage.googleapis.com/cloud-sql-connectors/cloud-sql-proxy/v2.15.2/cloud-sql-proxy.darwin.amd64
  sudo chmod +x /usr/local/bin/cloud-sql-proxy
}

install_pipx_packages() {
  cat $HOME/git/installation/pipx_packages | xargs -n 1 pipx install
  pipx inject mdformat mdformat-gfm
}
