curl -sS https://raw.githubusercontent.com/alexhokl/installation/master/versions-on-github | bash
curl -sS https://raw.githubusercontent.com/alexhokl/installation/master/debian/functions | bash

install_nodejs
install_bat
install_slack
install_remarkable
install_azure_data_studio
install_hexyl
install_octant
install_step
install_minikube
install_python
install_nvim
install_flutter
install_k9s
install_popeye
install_android_studio
install_azcopy
install_kubectx
install_icdiff
install_lolcat
install_have
install_light
install_speedtest
install_stern
install_sampler
install_hey
install_nuget
install_docker_compose
install_sqlpackage
install_vault
install_sc_im
install_vscode_extensions
install_ruby
install_vim
install_git
install_gh
install_go
install_bb_pr
install_terraform
install_lens
install_fzf
install_krew
install_pandoc
install_kind
install_code_server

